Update sonatype maven repository to use https in _maven_install
This is now a requirement of sonatype as of 01/15/2020

  https://support.sonatype.com/hc/en-us/articles/360041287334

It's currently causing failures on travis. In particular, builds that passed 2 days ago are now failing today (https://travis-ci.org/google/dagger/builds/636502706):

WARNING: Download from http://repo1.maven.org/maven2/com/squareup/javapoet/1.11.1/javapoet-1.11.1.jar failed: class GET returned 501 HTTPS Required

ERROR: An error occurred during the fetch of repository 'com_squareup_javapoet':

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=290067348