Bump Bazel to 8.1.1.
This requires regenerating the lock file for Flogger, which was upgrading from an old enough version that the existing lock file was not recognized.

As part of the Flogger update, I noticed this warning:

```
WARNING: For repository 'rules_java', the root module requires module version rules_java@7.12.1, but got rules_java@8.6.1 in the resolved dependency graph. Please update the version in your MODULE.bazel or set --check_direct_dependencies=off
```

So I bumped the version of `rules_java` there, too.

Also, the Flogger tests started failing from class-version problems:

```
java.lang.UnsupportedClassVersionError: com/google/common/flogger/backend/KeyValueFormatterTest has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

So I set up the build to target Java 8. (This presumably makes a lot of our existing per-target `javacopts` obsolete. I'll address that in followup cl/742400476.) I also filled in `--java_runtime_version=21` just as an attempt to get something deterministic. (Compare cl/734559216 for inject-common.)

RELNOTES=n/a
PiperOrigin-RevId: 742686185