Update Guava to 27.1.
This is necessary for my previous commit (the update to Truth 0.44) to work.
Without it, we see a NoSuchMethodError for Strings.lenientFormat.

Tested:
  Ran Dagger tests with the new bazel-common.

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=244710456